### PR TITLE
Compatibility fix for UE 5.0.1

### PR DESCRIPTION
**Pull request by MaximeDup**
Thanks Eidos for making it public, and for Shadow of the Tomb Raider .. !

### CODE REVIEW

**Comment by MaximeDup** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thilamb** [comment]
Thank you so much for contributing Maxime ! Some other users have been complaining about crashes with 5.0.1 and I haven't taken the time to fix it yet. This is great ! 

I'll just take more time to test your changes, and I'll integrate them asap.

**Comment by MaximeDup** [comment]
Tout le plaisir est pour moi.

**Comment by thilamb** [comment]
Encore merci ;)

**Pull request merged**
